In [175]:
#Project
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC, LinearSVC
from sklearn import svm

from sklearn.model_selection import cross_val_score, cross_val_predict, KFold
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics  import confusion_matrix, classification_report


twitter_file = "final_final_final_annotated_version.csv"

# Read in the csv into a pandas data frame.
dataset = pd.read_csv(twitter_file,encoding='utf-8')

print(dataset.shape)

#drop the NaN with 
#twitter_data.dropna(inplace=True)

print ("Number of observations :", len(dataset.index))
print ("Number of columns : ", len(dataset.columns))
print ("Headers : ", dataset.columns.values)

(2931, 6)
Number of observations : 2931
Number of columns :  6
Headers :  ['text' 'user' 'name' 'country' 'gender' 'sentiment']


In [140]:
dataset

text              user  \
0     @mhesne يا أخي ترى كرهنا سالفة قيادة المرأة لل...          @1477471   
1     @wwqs  مع استقدام سائقات وتوقيف السائقين ومنع ...        @iraghaad_   
2     #شيئ_ودك_يختفي_من_وطنك ادعياء حرية المرأة المز...      @zozoooo1402   
3     شنت المنظمات الحقوقية حملاتها الشرسة ضد السعود...  @SaudAlshamri_22   
4     أنا مع قيادة المرأة و في الوقت المناسب البلد ح...      @beeba_heart   
5     مع أو ضد ؟؟ قيادة المرأة بالسعودية ،،يلا خلونا...           @sohsbe   
6                          @Abudan94 ضد قيادة المرأة ☺>    @NasserHamad11   
7     قياده المرأة للسيارة بوابتها وصول قطار الرياض ...      @AbdulazizD1   
8     @impossible_333 ان دمج الشباب مع العوائل هو يش...       @amalmash70   
9     استحدثوا قوانين متناسبه مع المجتمع لاتقيدوا ال...          @mom_roo   
10    استفتاء عن قيادة المرأة.. ٣٩٪ غير مؤيدين ، ٢٧٪...         @OBahakam   
11    #قانون_تتمنى_تطبيقه\r  قيادة المرأة للسيارة  ب...      @ammoon_1401   
12    بمعنى لو انت مع قيادة المرأة لازم تكون ليبرالي...     @raed_alfassi   
13    عضوات الشورى سنقف كتلة واحدة مع قيادة المرأة ل...          @al_eiid   
14    @abdallah3663 لو شاهدت لقاء الشيخ الكلبانى كيف...         @MERE2013   
15    شاهد "تهاني عوده المشدق الجهني“ قيادة المرأة ع...            @am935   
16    ليش بعض الناس حاطين ببالهم ان قيادة المرأة= دع...        @amai8onna   
17                    اللي ضد قيادة المرأة .. وش حجتك !     @moonyfhoody1   
18    انا مع قيادة المرأة لسن ٣٥ وفوق وبشرط مايكون ع...            @ayot6   
19    #تناقض_الحكومة_السعودية\r\rتحارب الإختلاط وتمن...           @La7en2   
20    والله صرت اصرف على المواصلات مبالغ انا وبيتي ا...         @99asoomy   
21    #قيادة_26اكتوبر اقول زوجوا لوجين تركي وفكونا م...        @jewelm7md   
22    @mohnasser11 أنا أصلاً مع قيادة المرأة للسيارة...         @iYsulaim   
23    فيه واحد فِالآسك الا يطلعني مريضه و ما أعرف فا...      @sarangheaMG   
24    @ra7eeq_ma5toum لذا اعتقد ان قيادة النساء للسي...          @biboo11   
25    ماما تعرف تسوق ، بس مامعها رخصة ولا سيارة وفال...       @_I_October   
26    انقسامات في مجلس الشورى حول #قيادة المرأة #الس...         @afkarbiz   
27    رجل دين سعودي: قيادة المرأة سيارة «تؤذي المبيض...            @YFahm   
28    لماذا تريد المرأة قيادة السيارة مع أنها تقود ا...   @SeetahAlbuqami   
29    @mgreeh  اليوم جالسه اقول لابويا لو وافق المجل...        @2010amool   
...                                                 ...               ...   
2901  @HamodmeshriMesh @ASaci39 @nora_n2a انا مع قيا...  @HamodmeshriMesh   
2902  @_soamii لأن المطوع الكلب هو اللي حرمك من قياد...            @XY__R   
2903  @HistoryToLearn ثمة من يرفض حق المرأة في قيادة...         @a4bakeet   
2904  @AjelNews24 أقترح عليهم مع قيادة المرأة في كل ...  @yosf1717aljabri   
2905  من أجل هذه التصرفات نحن ضد قيادة المرأة .\rفتح...        @S3donvich   
2906  @hamsa66h @amalremy ومع قيادة المرأة بس انتي ا...      @abdaziz1399   
2907  @ombdr8 @AjelNews24 وانا بالعكس مع قيادة المرأ...     @turkixxgamer   
2908  @DrAbdullahKSA @xBL2ck @wm4488 @SaudiNews50 ان...            @Ym2iT   
2909          فتح ملف قياده المراه بالشورى. يتوافق مع..    @Mokhadram1566   
2910  @6XEUYJpdNzX1VHd @amfozan @5Molhm يناقشون قياد...        @msalroqi2   
2911  عند أول نقاش مع هذا الدكتور حول موضوع قيادة ال...        @mm_gohani   
2912  @REEMSulaiman80 زحمة سير وحوادث بتزيد و اصحاب ...         @saydlani   
2913  اووو وصل ترند 😂\r\rعندي مشكله وحدة مع قيادة ال...            @Mw4kK   
2914  سيدتى انتى مع ام ضد قرار قيادة المرأه للسياره ...   @alkhaleej_ahsa   
2915  اكثر شي عجبني بالهاشتاق هذا ان الي مع قيادة ال...         @MQueen33   
2916  والله انا مع وضد قيادة المراه الوضع مربك بعض ا...        @SshjSaroo   
2917  #الشعب_يويد_قياده_المراه \rكل زوج واخ وأب مع ق...    @asma_alamri29   
2918  امس خرجت مع الوالد السوق ولأول مرة نتكلم بخصوص...         @s_m_n_ez   
2919  @Rodi_Ca @HatoonKadi نسيت اخذ اذنك طال عمرك عل...           @rmr401   
2920  #الحجري_النساء_بربع_عقل لست مع قياده المراه لل...        @3lawy_305   
2921    مع او ضد قيادة المراه؟ \r#لسماح_للمراه_

In [141]:
dataset["text"][0]

'@mhesne يا أخي ترى كرهنا سالفة قيادة المرأة للسيارة الآن أغلب الشباب لايستطيعون شراء سيارة فكيف للمرأة تملك السيارة'

In [142]:
data = dataset["text"]

In [143]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vec = TfidfVectorizer()
X = tf_vec.fit_transform(data)
X.shape

(2931, 15110)

In [144]:
target = dataset["sentiment"]

In [145]:
target

0        n
1       ng
2       ng
3       ng
4        p
5        n
6       ng
7        n
8       ng
9        p
10       n
11       p
12       n
13       n
14       n
15       n
16       p
17       p
18       p
19       p
20       p
21       p
22       p
23       p
24       p
25       n
26       n
27       n
28       n
29       p
        ..
2901     p
2902     p
2903     p
2904     n
2905    ng
2906     p
2907     p
2908     p
2909     n
2910     n
2911     n
2912    ng
2913     n
2914     n
2915     n
2916     n
2917     n
2918     n
2919     n
2920     n
2921     n
2922     n
2923     n
2924     n
2925     n
2926     n
2927     n
2928    ng
2929    ng
2930    ng
Name: sentiment, Length: 2931, dtype: object

## 3 Classifiers: Data [Tweets] vs Target [Sentiment]

In [156]:
# Training Phase
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size=0.20, random_state=10)


In [187]:
#Classifier 1: BernoulliNB
from sklearn.naive_bayes import BernoulliNB

classifier_Ber = BernoulliNB().fit(X_train,y_train)
print("\nBernoulliNB accuracy: %.2f" %classifier_Ber.score(X_test, y_test))

results_Ber = cross_val_score(classifier_Ber, X_train,y_train, cv=10)
print("\n10-fold cross-validation:")
print(results_Ber)
print("The average accuracy of the BernoulliNB classifier is : %.2f" % np.mean(results_Ber))
print("\nConfusion matrix of the BernoulliNB classifier:")
predicted_Ber = classifier_Ber.predict(X_test)
print(confusion_matrix(y_test,predicted_Ber))
print("\nClassification_report of the BernoulliNB classifier:")
print(classification_report(y_test,predicted_Ber))
print("----------------------------------------------------------------------------")


BernoulliNB accuracy: 0.57

10-fold cross-validation:
[0.55508475 0.5720339  0.55319149 0.56410256 0.58119658 0.52991453
 0.53846154 0.58119658 0.58547009 0.62660944]
The average accuracy of the BernoulliNB classifier is : 0.57

Confusion matrix of the BernoulliNB classifier:
[[114   0  79]
 [ 44   7  79]
 [ 50   0 214]]

Classification_report of the BernoulliNB classifier:
             precision    recall  f1-score   support

          n       0.55      0.59      0.57       193
         ng       1.00      0.05      0.10       130
          p       0.58      0.81      0.67       264

avg / total       0.66      0.57      0.51       587

----------------------------------------------------------------------------


In [186]:
#Classifier 2: SVM

classifier_svm = svm.SVC(kernel='linear', C=1).fit(X_train,y_train)
print("SVM accuracy: %.2f"%classifier_svm.score(X_test, y_test))

results_svm = cross_val_score(classifier_svm, X,target, cv=10)
print("\n10-fold cross-validation:")
print(results_svm)
print("The average accuracy of the SVM classifier is : %.2f" % np.mean(results_svm))
print("\nConfusion matrix of the SVM classifier:")
predicted_svm = classifier_svm.predict(X_test)
print(confusion_matrix(y_test,predicted_svm))
print("\nClassification_report of SVM classifier:")
print(classification_report(y_test,predicted_svm))
print("----------------------------------------------------------------------------")


SVM accuracy: 0.60

10-fold cross-validation:
[0.58843537 0.58843537 0.6292517  0.61904762 0.61904762 0.54607509
 0.62457338 0.55136986 0.58561644 0.66323024]
The average accuracy of the SVM classifier is : 0.60

Confusion matrix of the SVM classifier:
[[115  10  68]
 [ 32  39  59]
 [ 53  11 200]]

Classification_report of SVM classifier:
             precision    recall  f1-score   support

          n       0.57      0.60      0.59       193
         ng       0.65      0.30      0.41       130
          p       0.61      0.76      0.68       264

avg / total       0.61      0.60      0.59       587

----------------------------------------------------------------------------


In [185]:
#Classifier 3: Logistic 
classifier_log=  LogisticRegression().fit(X_train,y_train)
print("Logisitic Accuracy: %.2F"%classifier_log.score(X_test, y_test))

results_log = cross_val_score(classifier_log, X,target, cv=10)
print("\n10-fold cross-validation:")
print(results_log)
print("The average accuracy of the SVM classifier is : %.2f" % np.mean(results_log))
print("\nConfusion matrix of the SVM classifier:")
predicted_log= classifier_log.predict(X_test)
print(confusion_matrix(y_test,predicted_log))
print("\nClassification_report of SVM classifier:")
print(classification_report(y_test,predicted_log))
print("----------------------------------------------------------------------------")

Logisitic Accuracy: 0.61

10-fold cross-validation:
[0.56122449 0.5952381  0.60544218 0.62244898 0.63605442 0.5221843
 0.58361775 0.55821918 0.58219178 0.64604811]
The average accuracy of the SVM classifier is : 0.59

Confusion matrix of the SVM classifier:
[[113   8  72]
 [ 34  35  61]
 [ 50   5 209]]

Classification_report of SVM classifier:
             precision    recall  f1-score   support

          n       0.57      0.59      0.58       193
         ng       0.73      0.27      0.39       130
          p       0.61      0.79      0.69       264

avg / total       0.62      0.61      0.59       587

----------------------------------------------------------------------------


## 3 Classifiers: Data [Tweets] vs Target [gender]

In [183]:
# Training Phase
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, target2, test_size=0.20, random_state=10)

In [191]:
#Classifier 1: BernoulliNB
from sklearn.naive_bayes import BernoulliNB

classifier_Ber2 = BernoulliNB().fit(X_train2,y_train2)
print("\nBernoulliNB accuracy: %.2f" %classifier_Ber2.score(X_test2, y_test2))

results_Ber2 = cross_val_score(classifier_Ber2, X_train2,y_train2, cv=10)
print("\n10-fold cross-validation:")
print(results_Ber2)
print("The average accuracy of the BernoulliNB classifier is : %.2f" % np.mean(results_Ber2))
print("\nConfusion matrix of the BernoulliNB classifier:")
predicted_Ber2 = classifier_Ber2.predict(X_test2)
print(confusion_matrix(y_test2,predicted_Ber2))
print("\nClassification_report of the BernoulliNB classifier:")
print(classification_report(y_test2,predicted_Ber2,target_names=['f','m','p']))
print("----------------------------------------------------------------------------")


BernoulliNB accuracy: 0.53

10-fold cross-validation:
[0.56962025 0.56962025 0.5720339  0.58050847 0.56170213 0.58119658
 0.58369099 0.59051724 0.59482759 0.58189655]
The average accuracy of the BernoulliNB classifier is : 0.58

Confusion matrix of the BernoulliNB classifier:
[[  0   0   0   3   8   0]
 [  0   0   0   1  29   0]
 [  0   0   0   0   5   0]
 [  0   0   0   7 200   0]
 [  0   0   0  10 307   0]
 [  0   0   0   0  17   0]]

Classification_report of the BernoulliNB classifier:
             precision    recall  f1-score   support

          f       0.00      0.00      0.00        11
          m       0.00      0.00      0.00        30
          p       0.00      0.00      0.00         5

avg / total       0.41      0.53      0.40       587

----------------------------------------------------------------------------


/Users/abdullah/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1428: UserWarning: labels size, 6, does not match size of target_names, 3
  .format(len(labels), len(target_names))
/Users/abdullah/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [195]:
#Classifier 2: SVM

classifier_svm2 = svm.SVC(kernel='linear', C=1).fit(X_train2,y_train2)
print("SVM accuracy: %.2f"%classifier_svm2.score(X_test2, y_test2))

results_svm2 = cross_val_score(classifier_svm2, X,target2, cv=10)
print("\n10-fold cross-validation:")
print(results_svm2)
print("The average accuracy of the SVM classifier is : %.2f" % np.mean(results_svm2))
print("\nConfusion matrix of the SVM classifier:")
predicted_svm2 = classifier_svm2.predict(X_test2)
print(confusion_matrix(y_test2,predicted_svm2))
print("\nClassification_report of SVM classifier:")
print(classification_report(y_test2,predicted_svm2,target_names=['f','m','p']))
print("----------------------------------------------------------------------------")


SVM accuracy: 0.58

10-fold cross-validation:
[0.58445946 0.60472973 0.57823129 0.63822526 0.60068259 0.60750853
 0.65187713 0.57876712 0.59793814 0.5862069 ]
The average accuracy of the SVM classifier is : 0.60

Confusion matrix of the SVM classifier:
[[  1   0   0   3   7   0]
 [  1   0   0   2  27   0]
 [  0   0   0   0   1   4]
 [  0   0   0  34 172   1]
 [  0   0   0  19 298   0]
 [  0   0   0   0  12   5]]

Classification_report of SVM classifier:
             precision    recall  f1-score   support

          f       0.50      0.09      0.15        11
          m       0.00      0.00      0.00        30
          p       0.00      0.00      0.00         5

avg / total       0.54      0.58      0.49       587

----------------------------------------------------------------------------


/Users/abdullah/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1428: UserWarning: labels size, 6, does not match size of target_names, 3
  .format(len(labels), len(target_names))
/Users/abdullah/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [193]:
#Classifier 3: Logistic 
classifier_log2=  LogisticRegression().fit(X_train2,y_train2)
print("Logisitic Accuracy: %.2F"%classifier_log2.score(X_test2, y_test2))

results_log2 = cross_val_score(classifier_log2, X,target2, cv=10)
print("\n10-fold cross-validation:")
print(results_log2)
print("The average accuracy of the SVM classifier is : %.2f" % np.mean(results_log2))
print("\nConfusion matrix of the SVM classifier:")
predicted_log2= classifier_log2.predict(X_test2)
print(confusion_matrix(y_test2,predicted_log2))
print("\nClassification_report of SVM classifier:")
print(classification_report(y_test2,predicted_log2))
print("----------------------------------------------------------------------------")

Logisitic Accuracy: 0.57

10-fold cross-validation:
[0.5777027  0.59459459 0.59863946 0.60750853 0.59385666 0.60068259
 0.59726962 0.56164384 0.58419244 0.57931034]
The average accuracy of the SVM classifier is : 0.59

Confusion matrix of the SVM classifier:
[[  1   0   0   2   8   0]
 [  1   0   0   0  29   0]
 [  0   0   0   0   1   4]
 [  0   0   0  18 189   0]
 [  0   0   0   7 310   0]
 [  0   0   0   0  14   3]]

Classification_report of SVM classifier:
             precision    recall  f1-score   support

          F       0.50      0.09      0.15        11
          M       0.00      0.00      0.00        30
          P       0.00      0.00      0.00         5
          f       0.67      0.09      0.15       207
          m       0.56      0.98      0.71       317
          p       0.43      0.18      0.25        17

avg / total       0.56      0.57      0.45       587

----------------------------------------------------------------------------


/Users/abdullah/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [196]:
from sklearn.decomposition import NMF, LatentDirichletAllocation
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [197]:
f = open('tweets.txt', encoding='utf-8')

In [198]:
stopwords_list = stopwords.words('arabic')

vectorizer = CountVectorizer(stop_words = stopwords_list)
transformer = TfidfTransformer()

In [199]:
trainVectorizerArray = vectorizer.fit_transform(f).toarray()

In [200]:
tf_feature_names = vectorizer.get_feature_names()

In [201]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])
        print(message)
    print()

In [202]:
n_samples = 2000
n_features = 1000
n_components = 20
n_top_words = 7
lda = LatentDirichletAllocation(n_components=n_components, max_iter=5,
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0)

In [203]:
lda.fit(trainVectorizerArray)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=5, mean_change_tol=0.001,
             n_components=20, n_jobs=1, n_topics=None, perp_tol=0.1,
             random_state=0, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [204]:
print_top_words(lda,tf_feature_names,n_top_words)

Topic #0: قيادة المرأة والله رفض السعودية الشورى الرجال
Topic #1: قيادة المرأة ضد انا للسيارة co http
Topic #2: https co سعودي سيارة بن دين سامي
Topic #3: بكره بالله الشعب_يويد_قياده_المراه الان سواقين سلمان hatoonkadi
Topic #4: قياده_المراه_قادمه قياده_المراه_فساد_للمجتمع آمين واقف ابسط الحجري_النساء_بربع_عقل حلول
Topic #5: الموضوع بلا لجين_على_الحدود النهاية فرق النساء قصيدة
Topic #6: الحكومة قمة لسماح_للمراه_بالقياده لأني بخصوص الخلوه أسوق
Topic #7: قياده_المراه_للسياره كلنا_مع_قياده_المراه_السعوديه طبعا loujainhathloul المفاسد عربي اليوم
Topic #8: اشوف دولة المجتمع_مع_قياده_المراه وصلت معظم مكة مؤيدين
Topic #9: الولاية مشكلة كلكم رعيته اع وكلكم حرية
Topic #10: no فاهم سايق_يختطف_طالبه_ويغتصبها يفهمون قناة اطالب العلمانية
Topic #11: الهيئة كثر وضع amrtsa للمجتمع بناتنا حريم_بيتي_لن_يقودوا
Topic #12: سيارتي الملك_ينتصر_لقياده_المراه حظي ددسن كاشخه وتهايط منسمه
Topic #13: قيادة_26اكتوبر الرجل واضح سواقه تقود السيارة قسم
Topic #14: حول نبي أوبر كريم نقاش تغير نطلب_القياده_وكمال_الاهليه